version: '2'
services:
  zipkin:
    image: openzipkin/zipkin:2.4.4
    container_name: zipkin
    environment:
    - STORAGE_TYPE=mysql
    - MYSQL_DB=zipkin
    - MYSQL_USER=root
    - MYSQL_PASS=123456
    - MYSQL_HOST=mysql
    - MYSQL_TCP_PORT=3306
    ports:
    - 8082:9411
    networks:
    - default
    - app_net
networks:
  app_net:
    external: true