version: '3'
services:
  web:
    image: licerlee/javaweb:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.7'
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
    - 8000:8080
    networks:
    - webnet
networks:
  webnet: 
  